fix: Support for plural translation forms in translated python
If there is Python code doing:
```
Object.tr("%n apple(s)", None, 2)
```

And I run:
```
$ qgis-plugin-ci push-translation $TX_TOKEN
```

I get an exception:
```
transifex.api.exceptions.UploadException: English pluralized strings should contain 2 plurals. Instead, on string '<translation><numerusform/></translation>' we found 1
```

The produced output by `pylupdate5` in the `.ts` file is:
```
<message numerus="yes">
  <source>%n apple(s)</source>
  <translation type="unfinished">
    <numerusform></numerusform>
  </translation>
</message>
```

We assume that the source language is English.

The problem is that English has 2 plural forms and they must be specified as part of the `.ts` file as two separate tags:
```
<message numerus="yes">
  <source>%n apple(s)</source>
  <translation type="unfinished">
    <numerusform></numerusform>
    <numerusform></numerusform>
  </translation>
</message>
```

While the suggested solution is far from beautiful and optimal, the other explored options did not work better:

1) replace `pylupdate5` with `lupdate` - according to the docs (https://doc.qt.io/qt-6/linguist-lupdate.html), `lupdate` should parse Python without an issue, but this is not the case, many errors due to failed Python parsing happened:
```
tr() cannot be called without context
Unterminated C++ string
```
2) parsing the XML and adding the new tag looks like an overkill, so I stick with a simple search and replace.
3) removing the `<numerusform></numerusform>` from the `.ts` file caused:
```
transifex.api.exceptions.UploadException: English pluralized strings should contain 2 plurals. Instead, on string '<translation><numerusform/></translation>' we found 0
```
4) seems that `lupdate` has a nice set of parameters that can help, but are not available in `pylupdate5` even after looking at it's internals:
```
       -source-language <language>[_<region>]
              Specify/override the language of the source strings. Defaults to POSIX if not specified and the file does not name it yet.

       -target-language <language>[_<region>]
              Specify/override the language of the translation.  The target language is guessed from the file name if this option is not specified and the file contents name no language yet.

```